version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: application:contact_resolve
    container_name: app_container
    command: gunicorn gsecart.wsgi:application --bind 0.0.0.0:8000

